# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: nodejs:14

dependencies:
    nodejs:
        tiddlywiki: "^5.1.23"

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
#relationships:
 # database: "db:mysql"

#hooks 

hooks:
  
  build: |
    echo "title: build_greetings" >> build_greetings.tid
    echo "type: application/json" >> build_greetings.tid
    echo "projectid: $PLATFORM_PROJECT" >> build_greetings.tid
    echo "appdirectory: $PLATFORM_APP_DIR" >> build_greetings.tid
    echo "test: hi 714pm" >> build_greetings.tid
    echo $'\n' >> build_greetings.tid
    V=$(echo $PLATFORM_APPLICATION | base64 --decode | json_pp)
    echo "$V" >> build_greetings.tid
  
  deploy: |
    cp build_greetings.tid wiki12/tiddlers


# The configuration of app when it is exposed to the web.
web:
  commands:
   start: tiddlywiki wiki11 --init server

# The size of the persistent disk of the application (in MB).
disk: 512

mounts:
     'wiki12':
        source: local
        source_path: wiki12