# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://www.{default}/dash":
    type: upstream
    upstream: "dashapp:http"

"https://{default}/dash":
    type: redirect
    to: "https://www.{default}/dash"
